package com.example.postsapi.model;

import com.example.postsapi.bean.UserBean;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;

@Entity
@Table(name="posts")
public class Post {

    @Id
    @Column
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(notes = "An auto-generated integer denoting the post ID. This field is not generated by the user.")
    private int id;

    @Column(nullable = false)
    @ApiModelProperty(notes = "A user-generated title for the post. This field is required.")
    private String title;

    @Column
    @ApiModelProperty(notes = "A user-generated description for the post. This field is not required.")
    private String description;

    @Column
    @ApiModelProperty(notes = "An auto-generated integer denoting the user ID. This field is not generated by the user.")
    private int user_id;

    @Transient
    @ApiModelProperty(required = true, hidden=true, notes = "Used for feign calls")
    private UserBean user;

    public Post() {}

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getUser_id() {
        return user_id;
    }

    public void setUser_id(int user_id) {
        this.user_id = user_id;
    }

    public UserBean getUser() {
        return user;
    }

    public void setUser(UserBean user) {
        this.user = user;
    }
}
