version: '3'

services:
  eureka:
    # image: maven:3.6.1-jdk-8
    build: ./eureka-server
    ports:
      - '8761:8761'
    working_dir: /app
    volumes:
      - ./eureka-server:/app
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - TERM=xterm-256color`
  api-gateway:
    # image: maven:3.6.1-jdk-8
    build: ./api-gateway
    ports:
      - '8080:8080'
    working_dir: /app
    volumes:
      - ./api-gateway:/app
    depends_on:
      - eureka
      - postgresdev
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - TERM=xterm-256color`
  users-api:
    # image: maven:3.6.1-jdk-8
    build: ./users-api
    ports:
      - '8081:8081'
    working_dir: /app
    volumes:
      - ./users-api:/app
    depends_on:
      - eureka
      - postgresdev
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - TERM=xterm-256color`
  posts-api:
    # image: maven:3.6.1-jdk-8
    build: ./posts-api
    ports:
      - '8082:8082'
    working_dir: /app
    volumes:
      - ./posts-api:/app
    depends_on:
      - eureka
      - postgresdev
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  comments-api:
    # image: maven:3.6.1-jdk-8
    build: ./comments-api
    ports:
      - '8083:8083'
    working_dir: /app
    volumes:
      - ./comments-api:/app
    depends_on:
      - eureka
      - postgresdev
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  postgresdev:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pgdev

