zuul:
  routes:
    user-login:
      path: /login
      stripPrefix: false
      serviceId: user
    user-signup:
      path: /signup
      stripPrefix: false
      serviceId: user

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  connection-timeout: 3000
  eureka:
    enabled: true

