zuul:
  routes:
    login:
      path: /login/**
      serviceId: user
      strip-prefix: false
    signup:
      path: /signup/**
      serviceId: user
      strip-prefix: false

ribbon:
  ReadTimeout: 60000
  connection-timeout: 3000
  eureka:
    enabled: true

